### ISSUE TITLE
Feature: Append repository locations to `dcd.conf`

### ISSUE THREAD

**Issue by joebonrichie** [serpent-os/onboarding#2]
This should help anyone setting a dlang LSP (namely `serve-d`). Serve-d will auto start `dcd-server` for auto-completion support. By default dcd-server will only include the stdlib location. Additional locations can be searched by adding them to the dcd config file.

As onboarding knows the locations of the serpent tooling repositories it could append them to the `~/.config/dcd/dcd.conf` file. This will allow auto-completions to work OOTB for serpent tooling and reduce the setup needed for anyone using a dlang LSP.

**Comment by ermo** [comment]
Excellent idea!
